services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: howto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  php:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: howto
      PGUSER: app
      PGPASSWORD: secret
    command: ["php", "/app/bin/run.php"]

volumes:
  pgdata:
